# Generated by Django 5.0.4 on 2024-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cpf', models.TextField(max_length=15, primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('rua', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=60)),
                ('numero', models.TextField(max_length=5)),
                ('estado', models.TextField(max_length=20)),
            ],
        ),
    ]
