# Generated by Django 5.0.4 on 2024-04-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
